package dev.ngocta.pycharm.odoo;

public class OdooNames {
    public static final String MANIFEST_FILE_NAME = "__manifest__.py";
    public static final String MANIFEST_DEPENDS = "depends";
    public static final String MANIFEST_DATA = "data";
    public static final String MANIFEST_DEMO = "demo";
    public static final String MANIFEST_QWEB = "qweb";
    public static final String ODOO = "odoo";
    public static final String ADDONS = "addons";
    public static final String ODOO_ADDONS = "odoo.addons";
    public static final String MODEL_NAME = "_name";
    public static final String MODEL_INHERIT = "_inherit";
    public static final String MODEL_INHERITS = "_inherits";
    public static final String FIELD_TYPE_ID = "Id";
    public static final String FIELD_TYPE_BOOLEAN = "Boolean";
    public static final String FIELD_TYPE_INTEGER = "Integer";
    public static final String FIELD_TYPE_FLOAT = "Float";
    public static final String FIELD_TYPE_MONETARY = "Monetary";
    public static final String FIELD_TYPE_CHAR = "Char";
    public static final String FIELD_TYPE_TEXT = "Text";
    public static final String FIELD_TYPE_DATE = "Date";
    public static final String FIELD_TYPE_DATETIME = "Datetime";
    public static final String FIELD_TYPE_SELECTION = "Selection";
    public static final String FIELD_TYPE_MANY2ONE = "Many2one";
    public static final String FIELD_TYPE_ONE2MANY = "One2many";
    public static final String FIELD_TYPE_MANY2MANY = "Many2many";
    public static final String FIELD_PARAM_COMODEL_NAME = "comodel_name";
    public static final String FIELD_PARAM_RELATED = "related";
    public static final String FIELD_PARAM_COMPUTE = "compute";
    public static final String FIELD_PARAM_INVERSE = "inverse";
    public static final String FIELD_PARAM_SEARCH = "search";
    public static final String FIELD_PARAM_DEFAULT = "default";
    public static final String ENV = "env";
    public static final String MAPPED = "mapped";
    public static final String FILTERED = "filtered";
    public static final String BASE_MODEL_CLASS_QNAME = "odoo.models.BaseModel";
    public static final String ENVIRONMENT_CLASS_QNAME = "odoo.api.Environment";
    public static final String MODULE_BASE = "base";
    public static final String REF_QNAME = "odoo.api.Environment.ref";
}
